"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
type Status = "lead" | "active" | "vip" | "inactive";
type Customer = { _id: string; name: string; phone: string; email?: string; city?: string; status: Status; tags: string[]; source?: string; note?: string; createdAt?: string };
const labels: Record<Status, string> = { lead: "سرنخ", active: "فعال", vip: "ویژه", inactive: "غیرفعال" };
const input = "w-full rounded-xl border border-forest/10 bg-[#faf8f5] px-3 py-2.5 text-xs text-forest outline-none focus:border-forest/30";
export default function CustomersWorkspace() {
  const [items, setItems] = useState<Customer[]>([]), [q, setQ] = useState(""), [status, setStatus] = useState<"all" | Status>("all"), [loading, setLoading] = useState(true), [notice, setNotice] = useState(""), [creating, setCreating] = useState(false);
  const [form, setForm] = useState({ name: "", phone: "", email: "", city: "", source: "", note: "", status: "lead" as Status, tags: "" });
  const load = useCallback(async () => { setLoading(true); try { const params = new URLSearchParams(); if (q.trim()) params.set("q", q.trim()); if (status !== "all") params.set("status", status); const r = await fetch(`/api/customers?${params}`); const data = await r.json(); if (!r.ok) throw new Error(data.message); setItems(data.items || []); } catch (e) { setNotice(e instanceof Error ? e.message : "دریافت مشتریان ناموفق بود"); } finally { setLoading(false); } }, [q, status]);
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  const stats = useMemo(() => ({ total: items.length, active: items.filter((i) => i.status === "active").length, vip: items.filter((i) => i.status === "vip").length }), [items]);
  async function create(event: React.FormEvent) { event.preventDefault(); setNotice(""); try { const r = await fetch("/api/customers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, tags: form.tags.split(/[،,]/).map((v) => v.trim()).filter(Boolean) }) }); const data = await r.json(); if (!r.ok) throw new Error(data.message); setForm({ name: "", phone: "", email: "", city: "", source: "", note: "", status: "lead", tags: "" }); setCreating(false); await load(); } catch (e) { setNotice(e instanceof Error ? e.message : "ثبت مشتری ناموفق بود"); } }
  return <main className="min-h-screen bg-[#f6f3ee]"><div className="mx-auto max-w-[1380px] px-5 py-7 sm:px-8 lg:px-10"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-forest/10 pb-7"><div><p className="text-[10px] tracking-[.18em] text-brick" dir="ltr">CUSTOMER CRM</p><h1 className="mt-2 text-3xl font-medium text-forest">مدیریت مشتریان</h1><p className="mt-2 text-xs text-forest/45">ثبت مشتری، دسته‌بندی و پیگیری ارتباط‌ها در یک جا.</p></div><button onClick={() => setCreating(!creating)} className="rounded-xl bg-forest px-4 py-3 text-xs font-medium text-paper">{creating ? "بستن فرم" : "+ مشتری جدید"}</button></header>
  <div className="mt-5 grid gap-3 sm:grid-cols-3">{[[stats.total,"کل مشتریان"],[stats.active,"مشتری فعال"],[stats.vip,"مشتری ویژه"]].map(([value,label]) => <div key={String(label)} className="rounded-2xl border border-forest/10 bg-white/70 p-4"><b className="text-xl text-forest">{Number(value).toLocaleString("fa-IR")}</b><p className="mt-1 text-[10px] text-forest/40">{label}</p></div>)}</div>
  {creating && <form onSubmit={create} className="mt-5 grid gap-3 rounded-2xl border border-forest/10 bg-white/80 p-5 sm:grid-cols-2"><input required className={input} placeholder="نام و نام خانوادگی *" value={form.name} onChange={(e) => setForm({...form,name:e.target.value})}/><input required className={input} dir="ltr" placeholder="شماره تماس *" value={form.phone} onChange={(e) => setForm({...form,phone:e.target.value})}/><input className={input} dir="ltr" placeholder="ایمیل" value={form.email} onChange={(e) => setForm({...form,email:e.target.value})}/><input className={input} placeholder="شهر" value={form.city} onChange={(e) => setForm({...form,city:e.target.value})}/><input className={input} placeholder="منبع آشنایی (اینستاگرام، نمایشگاه…)" value={form.source} onChange={(e) => setForm({...form,source:e.target.value})}/><select className={input} value={form.status} onChange={(e) => setForm({...form,status:e.target.value as Status})}>{Object.entries(labels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><input className={input} placeholder="برچسب‌ها، با ویرگول جدا کنید" value={form.tags} onChange={(e) => setForm({...form,tags:e.target.value})}/><textarea className={input} placeholder="یادداشت اولیه" value={form.note} onChange={(e) => setForm({...form,note:e.target.value})}/><button className="w-fit rounded-xl bg-forest px-5 py-3 text-xs text-paper">ثبت مشتری</button></form>}
  <section className="mt-5 overflow-hidden rounded-2xl border border-forest/10 bg-white/75"><div className="flex flex-wrap gap-3 border-b border-forest/10 p-4"><input className={`${input} max-w-sm`} placeholder="جست‌وجوی نام، تلفن، ایمیل…" value={q} onChange={(e)=>setQ(e.target.value)}/><select className={`${input} w-36`} value={status} onChange={(e)=>setStatus(e.target.value as "all"|Status)}><option value="all">همه وضعیت‌ها</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>{notice && <p className="m-4 rounded-xl bg-peach/30 px-3 py-2 text-xs text-brick">{notice}</p>}<div className="divide-y divide-forest/[.07]">{loading ? <p className="p-10 text-center text-xs text-forest/40">در حال دریافت…</p> : items.length ? items.map((item)=><article key={item._id} className="flex flex-wrap items-center gap-3 px-5 py-4"><div className="min-w-[180px] flex-1"><h2 className="text-sm font-medium text-forest">{item.name}</h2><p className="mt-1 text-[10px] text-forest/45" dir="ltr">{item.phone}{item.email ? ` · ${item.email}` : ""}</p></div><span className="text-[10px] text-forest/45">{item.city || "—"}</span><span className="rounded-full bg-sage/25 px-2.5 py-1 text-[9px] text-forest">{labels[item.status]}</span><div className="flex gap-1">{item.tags.map((tag)=><span key={tag} className="rounded bg-forest/[.06] px-2 py-1 text-[9px] text-forest/55">{tag}</span>)}</div></article>) : <p className="p-10 text-center text-xs text-forest/40">مشتری ثبت نشده است.</p>}</div></section></div></main>;
}
